version: '3.8'

services:

  database:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network

  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=5001
      - MONGODB_CONNECTIONSTRING=mongodb://database:27017/${MONGO_INITDB_DATABASE}
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-network

  nginx:
    build: ./nginx
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80" 
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mongo_data:
  
networks:
  app-network:
    driver: bridge